import os
import requests
import re
import json
import datetime
from dotenv import load_dotenv
from config import MODEL

load_dotenv()

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
GITHUB_REPOSITORY = os.environ.get("GITHUB_REPOSITORY") # Brauxo/Brauxo
ISSUE_NUMBER = os.environ.get("ISSUE_NUMBER")
ISSUE_AUTHOR = os.environ.get("ISSUE_AUTHOR")
ISSUE_BODY = os.environ.get("ISSUE_BODY")

if not all([GEMINI_API_KEY, GITHUB_TOKEN, GITHUB_REPOSITORY, ISSUE_NUMBER, ISSUE_AUTHOR, ISSUE_BODY]):
    print("Missing environment variables.")
    exit(1)

def check_rate_limit():
    today = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d')
    url = f"https://api.github.com/search/issues?q=repo:{GITHUB_REPOSITORY}+type:issue+created:{today}"
    headers = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
    res = requests.get(url, headers=headers)
    if res.status_code == 200:
        count = res.json().get("total_count", 0)
        if count > 5:
            return False
    return True

def get_dynamic_projects():
    username = GITHUB_REPOSITORY.split('/')[0]
    url = f"https://api.github.com/users/{username}/repos?sort=updated&per_page=6"
    headers = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
    res = requests.get(url, headers=headers)
    if res.status_code == 200:
        repos = res.json()
        projects_text = ""
        for idx, repo in enumerate(repos, 1):
            name = repo.get("name", "Unknown")
            desc = repo.get("description") or "No description"
            lang = repo.get("language") or "General"
            projects_text += f"- **{name}** ({lang}): {desc}\n"
        return projects_text.strip()
    return "Public repositories could not be retrieved at this time."

def call_gemini(prompt: str, model_name: str) -> Optional[str]:
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent?key={GEMINI_API_KEY}"
    payload = {"contents": [{"parts": [{"text": prompt}]}]}
    headers = {"Content-Type": "application/json"}
    try:
        response = requests.post(url, json=payload, headers=headers, timeout=30)
        if response.status_code == 200:
            data = response.json()
            return data["candidates"][0]["content"]["parts"][0]["text"].strip()
        print(f"[warning] Model {model_name} returned status {response.status_code}")
        return None
    except Exception as err:
        print(f"[error] Request to {model_name} failed: {err}")
        return None

def generate_answer(question: str) -> str:
    dynamic_projects = get_dynamic_projects()
    project_context = f"""
Public Repositories & Engineering Scope:
- Core Focus: AI Systems, Distributed Data Platforms, MLOps, Cloud Architecture.
- Technologies: Python, PySpark, GCP, AWS, Docker, Kubernetes, Terraform, dbt, BigQuery, PyTorch.

Active Repositories:
{dynamic_projects}
"""
    prompt = f"""
You are the interactive technical assistant for Owen Braux's GitHub profile (@{GITHUB_REPOSITORY}).
A developer (@{ISSUE_AUTHOR}) asks:
"{question}"

Context on repositories and technical scope:
{project_context}

Guidelines:
1. Tone: Professional, clear, concise, and helpful. No sci-fi roleplay or robotic jargon.
2. Focus strictly on technical architectures, open-source repositories, and developer tools. Do NOT disclose private personal info, resumes, or employer details. If asked about personal data, state politely: "I focus strictly on technical projects and public open-source architectures hosted on this profile."
3. Avoid self-aggrandizing language or talking in hyperbolic praise. Be factual and direct about the code and systems.
4. Keep the answer concise: maximum 3 to 4 sentences.
5. Respond in the same language as the question (French or English).
"""
    answer = call_gemini(prompt, MODEL)
    return answer or "The AI assistant is temporarily unavailable. Please retry shortly."

def comment_on_issue(answer):
    url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/issues/{ISSUE_NUMBER}/comments"
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    data = {"body": f"### 🤖 Assistant Response\n\n{answer}\n\n---\n*This response was generated by the profile agent and synced with the [README](https://github.com/{GITHUB_REPOSITORY}).*"}
    requests.post(url, headers=headers, json=data)

def close_issue():
    url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/issues/{ISSUE_NUMBER}"
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    data = {"state": "closed"}
    requests.patch(url, headers=headers, json=data)

def update_readme_qa(question, answer):
    # Clean the question (remove form labels/headers)
    clean_q_lines = []
    for line in question.split('\n'):
        line = line.strip()
        if not line or "ENTER_QUERY" in line or "Syntax check" in line or "Private data" in line or line.startswith("###"):
            continue
        clean_q_lines.append(line)
    clean_question = " ".join(clean_q_lines).strip()
    if not clean_question:
        clean_question = "Technical inquiry regarding projects and architecture."
        
    with open("README.md", "r", encoding="utf-8") as f:
        content = f.read()
        
    start_marker = "<!--QA_START-->"
    end_marker = "<!--QA_END-->"
    pattern = re.compile(f"{re.escape(start_marker)}(.*?){re.escape(end_marker)}", re.DOTALL)
    
    match = pattern.search(content)
    if match:
        current_qa = match.group(1).strip()
        
        # Format modern QA card
        new_block = f"> 💬 **@{ISSUE_AUTHOR}**: *\"{clean_question}\"*\n>\n> 🤖 {answer}"
        
        # Extract existing blocks
        blocks = [b.strip() for b in current_qa.split("<!--QA_SEP-->") if b.strip()]
        
        # Add new block at the beginning
        blocks.insert(0, new_block)
        
        # Keep last 3 exchanges for a cleaner layout
        blocks = blocks[:3]
        
        new_qa_section = "\n\n<!--QA_SEP-->\n\n".join(blocks)
        new_content = f"{start_marker}\n{new_qa_section}\n{end_marker}"
        updated_readme = pattern.sub(new_content, content)
        
        with open("README.md", "w", encoding="utf-8") as f:
            f.write(updated_readme)

if __name__ == "__main__":
    print(f"Processing question from @{ISSUE_AUTHOR}")
    
    # Prompt injection filter
    banned_keywords = ["ignore previous", "system prompt", "forget instructions", "bypass", "jailbreak", "dan"]
    if any(keyword in ISSUE_BODY.lower() for keyword in banned_keywords):
        print("Security violation detected.")
        comment_on_issue("Query rejected due to policy restrictions.")
        close_issue()
        exit(0)
        
    if not check_rate_limit():
        print("Rate limit exceeded.")
        comment_on_issue("Daily query limit reached (5/day). The assistant will accept new queries tomorrow.")
        close_issue()
        exit(0)
        
    answer = generate_answer(ISSUE_BODY)
    comment_on_issue(answer)
    close_issue()
    update_readme_qa(ISSUE_BODY, answer)
    print("Issue processed and README updated.")
