name: Update the readme with Latest AI Papers

on:
  schedule:
    # every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check repo
        uses: actions/checkout@v3

      - name: Fetch blog for AI papers
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "blog"
          feed_list: "http://export.arxiv.org/api/query?search_query=cat:cs.AI+OR+cat:cs.LG+OR+cat:cs.CV&sortBy=lastUpdatedDate&sortOrder=descending&max_results=5"
          max_post_count: 5
          template: "* [$title]($url) - _Published on $date_ \n"
          date_format: "mmmm d, yyyy"