name: Update the readme with Latest AI Papers

on:
  schedule:
    # every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Manual

jobs:
  update-papers:
    runs-on: ubuntu-latest
    steps:
      - name: Check repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install feedparser

      - name: Run Python script 
        run: python update_papers.py

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: Update latest AI/ML papers"
          file_pattern: README.md