name: Update the readme with Latest AI Papers

on:
  schedule:
    # every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Manual

jobs:
  update-nasa:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script 
        env:
          NASA_API_KEY: ${{secrets.NASA_API}}
        run: python update_nasa.py

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "schedule : new Nasa picture"
          file_pattern: README.md